### ISSUE TITLE
Doesn’t work with batteries providing power_now, not current_now

### ISSUE THREAD

**Issue by andrewshadura** [ssnover95/acpi_client#3]
Bails out with `Path is not a file.` on my system.
```sh
$ ls /sys/class/power_supply/BAT0/
alarm           charge_start_threshold  device@             energy_now    model_name  present        subsystem@  uevent
capacity        charge_stop_threshold   energy_full         hwmon2/       power/      serial_number  technology  voltage_min_design
capacity_level  cycle_count             energy_full_design  manufacturer  power_now   status         type        voltage_now
$ cat /sys/class/power_supply/BAT0/uevent
POWER_SUPPLY_NAME=BAT0
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=11100000
POWER_SUPPLY_VOLTAGE_NOW=11123000
POWER_SUPPLY_POWER_NOW=11478000
POWER_SUPPLY_ENERGY_FULL_DESIGN=23200000
POWER_SUPPLY_ENERGY_FULL=14630000
POWER_SUPPLY_ENERGY_NOW=5850000
POWER_SUPPLY_CAPACITY=39
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=45N1773
POWER_SUPPLY_MANUFACTURER=SANYO
POWER_SUPPLY_SERIAL_NUMBER=21069
```
I tried doing something like this, but it didn’t work correctly (not sure whether it’s my understanding of how `power_now` and `current_now` work, or just the matter of getting arithmetic right 🙂):
```diff
@@ -118,8 +129,15 @@ fn parse_capacity_supply(path: &path::Path) -> Result<BatteryInfo, AcpiClientErr
 /// * `path` - The path to the ACPI device.
 fn parse_energy_supply(path: &path::Path) -> Result<BatteryInfo, AcpiClientError> {
     let voltage = parse_file_to_i32(&path.join("voltage_now"), 1000)? as u32;
+    dbg!(voltage);
     let remaining_capacity = parse_file_to_i32(&path.join("energy_now"), 1000)? as u32 / voltage;
-    let present_rate = parse_file_to_i32(&path.join("current_now"), 1000)? as u32;
+    let present_rate = if let Ok(current_now) = parse_file_to_i32(&path.join("current_now"), 1000) {
+        current_now as u32
+    } else {
+        let power_now = parse_file_to_i32(&path.join("power_now"), 1)? as u32;
+        dbg!(power_now);
+        power_now / voltage
+    };
     let design_capacity =
         parse_file_to_i32(&path.join("energy_full_design"), 1000)? as u32 / voltage;
     let last_capacity = parse_file_to_i32(&path.join("energy_full"), 1000)? as u32 / voltage;
```

**Comment by andrewshadura** [comment]
I guess this code is worth of a study: https://gitlab.freedesktop.org/upower/upower/-/blob/master/src/linux/up-device-supply.c#L675

**Comment by ssnover** [comment]
I think your solution should work with the only change needing to change the second argument of `parse_file_to_i32` from 1 to 1000. My system reports all of the numbers in micro-units: microamps, microvolts, etc. It looks like your system does too (I would hope this one thing could be consistent between systems at least!). 

If you want to try that out and make sure it works I'd be happy to take a PR with the changes!

**Comment by duhdugg** [comment]
PR #4 should fix this.

The example code in this issue was used, with some modifications:

- existence of `power_now` is checked first, as kernel developers seem to have intended for `current_now` to be used only for backwards compatibility. See: [7faa144](https://github.com/torvalds/linux/commit/7faa144a518c456e2057918f030f50100144ccc6)
- the 2nd argument to `parse_file_to_i32` is `1000` in both cases, as suggested by @ssnover,  as units in both cases are reported in µWh
- there is no need to divide `power_now` by `voltage` here, as `power_now` already represents the present rate
